tasks:
     - name: Create a text file in opt directory using /bin/sh shell
         ansible.builtin.shell: echo "I am creating a new file" > /opt/new_file.txt
         become: true   # Ensure that the highest permissions are used on the remote host


